# Site settings
title:       "Vlad Alexandru Ionescu .com"
email:
author:      "Vlad Alexandru Ionescu"
description: "Co-founder and CTO of Sync Ninja. Ex-Google, Ex-VMware. Backend and scalability developer motivated by work that solves real-world problems."
baseurl:     ""
url:         "http://www.vladalexandruionescu.com"
date_format: "%b %-d, %Y"

# Google analytics
google_analytics: "UA-29072316-1"
google_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: "vlad-alexandru-ionescu"
bitbucket_username:
stackoverflow_id:
twitter_username: "VladAIonescu"
google_plus_id: "VladAlexandruIonescu"
linkedin_username: "vladalexandruionescu"
angellist_username: "vladaionescu"
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    "/:year/:month/:title.html"
paginate:     4
sass:
  compressed: true
gems:         [jekyll-paginate]
